config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  resources :questions do 
    resources :answers
  end

  post 'vote', to: 'answers#vote', as: 'vote'

end

app/models/answer.rb
class Answer < ActiveRecord::Base

  belongs_to :question
  
end

app/models/question.rb
class Question < ActiveRecord::Base

  has_many :answers

  def count_votes
    total = 0

    self.answers.each do |answer|
      total += answer.votes
    end
    
    return total
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    question = Question.find_by_id(params["question_id"])
    answer = Answer.new(answers_params)
    answer.save
    question.answers << answer
    redirect_to question_path(question.id)
  end

  def vote
    answer = Answer.find_by_id(params["id"])
    answer.votes += 1
    answer.save

    respond_to do |format|
      format.json { render json:
                        { "answer_id" => answer.id.to_json,
                          "answer_votes" => answer.votes.to_json }
                  }
    end
  end


private
  def answers_params
    params.require(:answer).permit(:response)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    questions = Question.order(created_at: :desc)
    @firstQuestion = questions.first
    @remainderOfQuestions = questions[1..-1]
  end
  
  def show
    @question = Question.find_by_id(params["id"])
  end

  def new
    @question = Question.new
  end

  def create
    question = Question.new(question_params)
    if question.save
      redirect_to question_path(question.id)
    end
  end

private
  def question_params
    params.require(:question).permit(:title, :query)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fundera</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/_question.html.haml
.link-to-question
  =link_to question.title, question_path(question.id)
.question-query
  = question.query

app/views/questions/index.html.haml
%h1
  Would you like to ask a question?

=link_to "New Question!", new_question_path

%h1
  All these questions are everybody's questions.

.first-question
  .title
    = @firstQuestion.title
  .query
    = @firstQuestion.query
  .total-answers
    = "Total Answers: #{@firstQuestion.answers.count}"
  .total-votes
    = "Total Votes: #{@firstQuestion.count_votes}"
  

.questions-list
  - @remainderOfQuestions.each do |question|
    = render 'question', :question =>question







  

app/views/questions/new.html.haml
%h1
  What's your new question?

= simple_form_for @question do |f|
  = f.input :title
  = f.input :query
  = f.button "submit"

app/views/questions/show.html.haml
%h1
  = @question.title
%h2  
  = @question.query

%h1
  Answers:

- @question.answers.each do |answer|
  .response
    = answer.response
    .total-votes-label
      Votes:
    .total-votes-value{id: "answer_" + answer.id.to_s}
      = answer.votes
    .up-vote{id: answer.id}
      +
    
    

%h1 
  Add Your Own Anwser!

= simple_form_for :answer, url: question_answers_path(@question.id) do |f|
  = f.input :response
  = f.submit

= link_to 'Return to All Questions', questions_path